# Generated by Django 3.2.4 on 2021-06-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cars_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='perfil',
            field=models.CharField(default='user', max_length=10),
            preserve_default=False,
        ),
    ]
