# Generated by Django 3.2.4 on 2021-06-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tokens_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='placa',
        ),
        migrations.AddField(
            model_name='cars',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
