# Generated by Django 3.2.4 on 2021-06-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210620_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
